# Day 1

In [2]:
import pandas as pd

In [3]:
pd.read_csv('../.ipynb_checkpoints/emp.csv')

    eno   ename  salary  deptno         doj
0    10   Amber    1000      10  14-05-2018
1     2    Amar    1000      10  22-03-2017
2     8   Sagar    1000      20  30-11-2020
3     4  Thomas    1000      10  18-08-2019
4     5    Jade    2000      10  10-02-2021
5     6   Smith    1000      10  01-12-2016
6     7  Robert    3000      20  25-05-2023
7     3    Nick    1000      30  15-09-2015
8     9   Naman    4000      30  20-01-2020
9     1   Vikas    1000      30  03-10-2017
10   11  Dennis   41000      30  05-01-2024
11   12   Karan    2200      20  16-06-2018

In [7]:
dataframe = pd.read_csv('../.ipynb_checkpoints/emp.csv')

In [8]:
dataframe

    eno   ename  salary  deptno         doj
0    10   Amber    1000      10  14-05-2018
1     2    Amar    1000      10  22-03-2017
2     8   Sagar    1000      20  30-11-2020
3     4  Thomas    1000      10  18-08-2019
4     5    Jade    2000      10  10-02-2021
5     6   Smith    1000      10  01-12-2016
6     7  Robert    3000      20  25-05-2023
7     3    Nick    1000      30  15-09-2015
8     9   Naman    4000      30  20-01-2020
9     1   Vikas    1000      30  03-10-2017
10   11  Dennis   41000      30  05-01-2024
11   12   Karan    2200      20  16-06-2018

In [9]:
type(dataframe)

pandas.DataFrame

In [10]:
df['eno']

0     10
1      2
2      8
3      4
4      5
5      6
6      7
7      3
8      9
9      1
10    11
11    12
Name: eno, dtype: int64

In [18]:
# if i want read  1 column need to use [] and it will be a series

series = df['eno']

In [12]:
series

0     10
1      2
2      8
3      4
4      5
5      6
6      7
7      3
8      9
9      1
10    11
11    12
Name: eno, dtype: int64

In [13]:
type(series)

pandas.Series

In [15]:
# if i want read more than 1 column need to use [[]]
df[['eno','ename']]

    eno   ename
0    10   Amber
1     2    Amar
2     8   Sagar
3     4  Thomas
4     5    Jade
5     6   Smith
6     7  Robert
7     3    Nick
8     9   Naman
9     1   Vikas
10   11  Dennis
11   12   Karan

In [17]:
type(df[['eno','ename']])

pandas.DataFrame

In [21]:
df = pd.read_csv('../.ipynb_checkpoints/emp.csv', delimiter=',')

In [22]:
df

    eno   ename  salary  deptno         doj
0    10   Amber    1000      10  14-05-2018
1     2    Amar    1000      10  22-03-2017
2     8   Sagar    1000      20  30-11-2020
3     4  Thomas    1000      10  18-08-2019
4     5    Jade    2000      10  10-02-2021
5     6   Smith    1000      10  01-12-2016
6     7  Robert    3000      20  25-05-2023
7     3    Nick    1000      30  15-09-2015
8     9   Naman    4000      30  20-01-2020
9     1   Vikas    1000      30  03-10-2017
10   11  Dennis   41000      30  05-01-2024
11   12   Karan    2200      20  16-06-2018

In [30]:
# my file is having all the columns but i want to read only few columns
df = pd.read_csv('../.ipynb_checkpoints/emp.csv', delimiter =',', usecols =['eno', 'ename'])

In [31]:
df

    eno   ename
0    10   Amber
1     2    Amar
2     8   Sagar
3     4  Thomas
4     5    Jade
5     6   Smith
6     7  Robert
7     3    Nick
8     9   Naman
9     1   Vikas
10   11  Dennis
11   12   Karan

# Day 2
# key functions and attribute in pandas

In [32]:
import pandas as pd
df = pd.read_csv('../.ipynb_checkpoints/emp.csv', delimiter =',', usecols = ['eno', 'ename', 'doj'])

In [33]:
df

    eno   ename         doj
0    10   Amber  14-05-2018
1     2    Amar  22-03-2017
2     8   Sagar  30-11-2020
3     4  Thomas  18-08-2019
4     5    Jade  10-02-2021
5     6   Smith  01-12-2016
6     7  Robert  25-05-2023
7     3    Nick  15-09-2015
8     9   Naman  20-01-2020
9     1   Vikas  03-10-2017
10   11  Dennis  05-01-2024
11   12   Karan  16-06-2018

In [34]:
type(df)

pandas.DataFrame

In [38]:
# select only eno and doj columns
columns_name = ['eno','doj']
df[columns_name]

    eno         doj
0    10  14-05-2018
1     2  22-03-2017
2     8  30-11-2020
3     4  18-08-2019
4     5  10-02-2021
5     6  01-12-2016
6     7  25-05-2023
7     3  15-09-2015
8     9  20-01-2020
9     1  03-10-2017
10   11  05-01-2024
11   12  16-06-2018

In [40]:
# select only 4th row
df.iloc[4]

eno               5
ename          Jade
doj      10-02-2021
Name: 4, dtype: object

In [42]:
df.head()

   eno   ename         doj
0   10   Amber  14-05-2018
1    2    Amar  22-03-2017
2    8   Sagar  30-11-2020
3    4  Thomas  18-08-2019
4    5    Jade  10-02-2021

In [45]:
# by default header is 0 
pd.read_csv('../.ipynb_checkpoints/emp.csv', delimiter =',', header = 0)

    eno   ename  salary  deptno         doj
0    10   Amber    1000      10  14-05-2018
1     2    Amar    1000      10  22-03-2017
2     8   Sagar    1000      20  30-11-2020
3     4  Thomas    1000      10  18-08-2019
4     5    Jade    2000      10  10-02-2021
5     6   Smith    1000      10  01-12-2016
6     7  Robert    3000      20  25-05-2023
7     3    Nick    1000      30  15-09-2015
8     9   Naman    4000      30  20-01-2020
9     1   Vikas    1000      30  03-10-2017
10   11  Dennis   41000      30  05-01-2024
11   12   Karan    2200      20  16-06-2018

In [48]:
# by default header is 0 but i want make header as 2nd line put header = 1
df = pd.read_csv('../.ipynb_checkpoints/emp.csv', delimiter =',', header = 1)

In [49]:
df

    10   Amber   1000  10.1  14-05-2018
0    2    Amar   1000    10  22-03-2017
1    8   Sagar   1000    20  30-11-2020
2    4  Thomas   1000    10  18-08-2019
3    5    Jade   2000    10  10-02-2021
4    6   Smith   1000    10  01-12-2016
5    7  Robert   3000    20  25-05-2023
6    3    Nick   1000    30  15-09-2015
7    9   Naman   4000    30  20-01-2020
8    1   Vikas   1000    30  03-10-2017
9   11  Dennis  41000    30  05-01-2024
10  12   Karan   2200    20  16-06-2018

In [50]:
# select only 4th row
df.iloc[4]

10                     6
Amber              Smith
1000                1000
10.1                  10
14-05-2018    01-12-2016
Name: 4, dtype: object

In [53]:
# select  4th row from the dataframe
row5 = df.iloc[4]

In [54]:
type(row5)

pandas.Series

In [55]:
# select 3rd and 4th row from df
row3_4 = df.iloc[2:4]

In [56]:
row3_4

   10   Amber  1000  10.1  14-05-2018
2   4  Thomas  1000    10  18-08-2019
3   5    Jade  2000    10  10-02-2021

In [64]:
# setting eno as index column (only for uniquely identified column i can set index column )
df = pd.read_csv('../.ipynb_checkpoints/emp.csv', delimiter =',', header = 0, index_col ='eno')

In [65]:
df

      ename  salary  deptno         doj
eno
1     Vikas    1000      30  03-10-2017
2      Amar    1000      10  22-03-2017
3      Nick    1000      30  15-09-2015
4    Thomas    1000      10  18-08-2019
5      Jade    2000      10  10-02-2021
6     Smith    1000      10  01-12-2016
7    Robert    3000      20  25-05-2023
8     Sagar    1000      20  30-11-2020
9     Naman    4000      30  20-01-2020
10    Amber    1000      10  14-05-2018
11   Dennis   41000      30  05-01-2024
12    Karan    2200      20  16-06-2018

In [66]:
# get me the record of eno = 9
df.loc[9]

ename          Naman
salary          4000
deptno            30
doj       20-01-2020
Name: 9, dtype: object

In [68]:
#get me eno from 6 to 9
# select *from emp where eno in(6,7,8,9)
df.loc[6:9]

      ename  salary  deptno         doj
eno
6     Smith    1000      10  01-12-2016
7    Robert    3000      20  25-05-2023
8     Sagar    1000      20  30-11-2020
9     Naman    4000      30  20-01-2020

In [70]:
#get me eno from 6 to 9 only column deptno and ename (i can't use index column eno)
# select eno,ename from emp where eno in(6,7,8,9)
df[['deptno','ename']].loc[6:9]

     deptno   ename
eno
6        10   Smith
7        20  Robert
8        20   Sagar
9        30   Naman

In [72]:
# read only eno,ename,doj as columns and get only 10 records
df = pd.read_csv('../.ipynb_checkpoints/emp.csv', delimiter=',', usecols=['eno', 'ename', 'doj'], header=0, nrows=10)
df

   eno   ename         doj
0    1   Vikas  03-10-2017
1    2    Amar  22-03-2017
2    3    Nick  15-09-2015
3    4  Thomas  18-08-2019
4    5    Jade  10-02-2021
5    6   Smith  01-12-2016
6    7  Robert  25-05-2023
7    8   Sagar  30-11-2020
8    9   Naman  20-01-2020
9   10   Amber  14-05-2018

In [77]:
# read only eno,ename,doj as columns and get only 10  to 12 records
df = pd.read_csv('../.ipynb_checkpoints/emp.csv', delimiter=',', usecols=['eno', 'ename', 'doj'], header=0, skiprows=range (1, 5), nrows=2)
df

   eno  ename         doj
0    5   Jade  10-02-2021
1    6  Smith  01-12-2016

In [80]:
# get the data types of the columns in the dataframe
df = pd.read_csv('../.ipynb_checkpoints/emp.csv')
df.dtypes

eno       int64
ename       str
salary    int64
deptno    int64
doj         str
dtype: object

In [107]:
# converting eno int to float
df = pd.read_csv('../.ipynb_checkpoints/emp.csv', dtype ={'eno':float})

In [108]:
df

     eno   ename  salary  deptno         doj
0    1.0   Vikas    1000      30  2017-10-03
1    2.0    Amar    1000      10  2017-03-22
2    3.0    Nick    1000      30  2015-09-15
3    4.0  Thomas    1000      10  2019-08-18
4    5.0    Jade    2000      10  2021-10-02
5    6.0   Smith    1000      10  2016-01-12
6    7.0  Robert    3000      20   2023-2-05
7    8.0   Sagar    1000      20  2020-03-11
8    9.0   Naman    4000      30  2020-02-01
9   10.0   Amber    1000      10  2018-04-05
10  11.0  Dennis   41000      30  2024-05-01
11  12.0   Karan    2200      20  2018-06-06

In [104]:
df.dtypes

eno       float64
ename         str
salary      int64
deptno      int64
doj           str
dtype: object

In [120]:
# converting doj into date format
df = pd.read_csv('../.ipynb_checkpoints/emp.csv', parse_dates =['doj'])

In [121]:
df.dtypes

eno                int64
ename                str
salary             int64
deptno             int64
doj       datetime64[us]
dtype: object

In [125]:
# extract month, year and date
df['doj'].dt.month
#df['doj'].dt.year

0     10
1      3
2      9
3      8
4     10
5      1
6      2
7      3
8      2
9      4
10     5
11     6
Name: doj, dtype: int32

In [131]:
# Low_Memory = True , by default it is True(when you want read whole file at once make it false)
df = pd.read_csv('../.ipynb_checkpoints/emp.csv', parse_dates =['doj'], low_memory=False)
df

    eno   ename  salary  deptno        doj
0     1   Vikas    1000      30 2017-10-03
1     2    Amar    1000      10 2017-03-22
2     3    Nick    1000      30 2015-09-15
3     4  Thomas    1000      10 2019-08-18
4     5    Jade    2000      10 2021-10-02
5     6   Smith    1000      10 2016-01-12
6     7  Robert    3000      20 2023-02-05
7     8   Sagar    1000      20 2020-03-11
8     9   Naman    4000      30 2020-02-01
9    10   Amber    1000      10 2018-04-05
10   11  Dennis   41000      30 2024-05-01
11   12   Karan    2200      20 2018-06-06

In [134]:
#encoding
df = pd.read_csv('../.ipynb_checkpoints/emp.csv', encoding='utf-8')
df

    eno   ename  salary  deptno         doj
0     1   Vikas    1000      30  2017-10-03
1     2    Amar    1000      10  2017-03-22
2     3    Nick    1000      30  2015-09-15
3     4  Thomas    1000      10  2019-08-18
4     5    Jade    2000      10  2021-10-02
5     6   Smith    1000      10  2016-01-12
6     7  Robert    3000      20   2023-2-05
7     8   Sagar    1000      20  2020-03-11
8     9   Naman    4000      30  2020-02-01
9    10   Amber    1000      10  2018-04-05
10   11  Dennis   41000      30  2024-05-01
11   12   Karan    2200      20  2018-06-06

In [135]:
df = pd.read_csv('../.ipynb_checkpoints/emp.csv', encoding ='latin1')
df

    eno   ename  salary  deptno         doj
0     1   Vikas    1000      30  2017-10-03
1     2    Amar    1000      10  2017-03-22
2     3    Nick    1000      30  2015-09-15
3     4  Thomas    1000      10  2019-08-18
4     5    Jade    2000      10  2021-10-02
5     6   Smith    1000      10  2016-01-12
6     7  Robert    3000      20   2023-2-05
7     8   Sagar    1000      20  2020-03-11
8     9   Naman    4000      30  2020-02-01
9    10   Amber    1000      10  2018-04-05
10   11  Dennis   41000      30  2024-05-01
11   12   Karan    2200      20  2018-06-06

In [2]:
import pandas as pd
df = pd.read_csv('../.ipynb_checkpoints/emp.csv', encoding ='ascii')
df

    eno   ename  salary  deptno         doj
0     1   Vikas    1000      30  2017-10-03
1     2    Amar    1000      10  2017-03-22
2     3    Nick    1000      30  2015-09-15
3     4  Thomas    1000      10  2019-08-18
4     5    Jade    2000      10  2021-10-02
5     6   Smith    1000      10  2016-01-12
6     7  Robert    3000      20   2023-2-05
7     8   Sagar    1000      20  2020-03-11
8     9   Naman    4000      30  2020-02-01
9    10   Amber    1000      10  2018-04-05
10   11  Dennis   41000      30  2024-05-01
11   12   Karan    2200      20  2018-06-06

# filtering (similar to where clause in SQL)

In [16]:
# get me emp who are getting more than 3000 
# select *from emp where salary > 3000
salary_3000 = df['salary'] > 3000

In [8]:
# we are getting only true or false 
df.salary_3000

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10     True
11    False
Name: salary, dtype: bool

In [9]:
# to see all the data 
df[salary_3000]

    eno   ename  salary  deptno         doj
8     9   Naman    4000      30  2020-02-01
10   11  Dennis   41000      30  2024-05-01

In [17]:
# get me emp who are getting more than 2000 and belongs to dept no 20
# select *from emp where salary > 3000 and deptno = 20
salary_2000 = df['salary'] > 2000 
deptno_20 = df['deptno'] == 20
final_filter = salary_2000 & deptno_20

In [14]:
final_filter

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11     True
dtype: bool

In [15]:
df[final_filter]

    eno   ename  salary  deptno         doj
6     7  Robert    3000      20   2023-2-05
11   12   Karan    2200      20  2018-06-06

# sorting (ascending /descending)

In [19]:
# sort based on salary column by asc
df.sort_values (by = 'salary')
# or
df.sort_values(by = 'salary', ascending = True)

    eno   ename  salary  deptno         doj
0     1   Vikas    1000      30  2017-10-03
1     2    Amar    1000      10  2017-03-22
2     3    Nick    1000      30  2015-09-15
3     4  Thomas    1000      10  2019-08-18
5     6   Smith    1000      10  2016-01-12
7     8   Sagar    1000      20  2020-03-11
9    10   Amber    1000      10  2018-04-05
4     5    Jade    2000      10  2021-10-02
11   12   Karan    2200      20  2018-06-06
6     7  Robert    3000      20   2023-2-05
8     9   Naman    4000      30  2020-02-01
10   11  Dennis   41000      30  2024-05-01

In [20]:
# sort based on salary column by desc
df.sort_values (by = 'salary')
# or
df.sort_values(by = 'salary', ascending = False)

    eno   ename  salary  deptno         doj
10   11  Dennis   41000      30  2024-05-01
8     9   Naman    4000      30  2020-02-01
6     7  Robert    3000      20   2023-2-05
11   12   Karan    2200      20  2018-06-06
4     5    Jade    2000      10  2021-10-02
2     3    Nick    1000      30  2015-09-15
1     2    Amar    1000      10  2017-03-22
0     1   Vikas    1000      30  2017-10-03
3     4  Thomas    1000      10  2019-08-18
5     6   Smith    1000      10  2016-01-12
7     8   Sagar    1000      20  2020-03-11
9    10   Amber    1000      10  2018-04-05

In [22]:
# sort based on deptno in ascending and salary  by desc
df.sort_values(by =['deptno','salary'], ascending = [True,False])

    eno   ename  salary  deptno         doj
4     5    Jade    2000      10  2021-10-02
1     2    Amar    1000      10  2017-03-22
3     4  Thomas    1000      10  2019-08-18
5     6   Smith    1000      10  2016-01-12
9    10   Amber    1000      10  2018-04-05
6     7  Robert    3000      20   2023-2-05
11   12   Karan    2200      20  2018-06-06
7     8   Sagar    1000      20  2020-03-11
10   11  Dennis   41000      30  2024-05-01
8     9   Naman    4000      30  2020-02-01
0     1   Vikas    1000      30  2017-10-03
2     3    Nick    1000      30  2015-09-15

# doubt session

In [24]:
# sort index
df = pd.read_csv('../.ipynb_checkpoints/emp.csv', parse_dates =['doj'], index_col='eno')

In [28]:
df.sort_index(ascending = False)

      ename  salary  deptno        doj
eno
12    Karan    2200      20 2018-06-06
11   Dennis   41000      30 2024-05-01
10    Amber    1000      10 2018-04-05
9     Naman    4000      30 2020-02-01
8     Sagar    1000      20 2020-03-11
7    Robert    3000      20 2023-02-05
6     Smith    1000      10 2016-01-12
5      Jade    2000      10 2021-10-02
4    Thomas    1000      10 2019-08-18
3      Nick    1000      30 2015-09-15
2      Amar    1000      10 2017-03-22
1     Vikas    1000      30 2017-10-03

In [26]:
df.sort_index()

      ename  salary  deptno        doj
eno
1     Vikas    1000      30 2017-10-03
2      Amar    1000      10 2017-03-22
3      Nick    1000      30 2015-09-15
4    Thomas    1000      10 2019-08-18
5      Jade    2000      10 2021-10-02
6     Smith    1000      10 2016-01-12
7    Robert    3000      20 2023-02-05
8     Sagar    1000      20 2020-03-11
9     Naman    4000      30 2020-02-01
10    Amber    1000      10 2018-04-05
11   Dennis   41000      30 2024-05-01
12    Karan    2200      20 2018-06-06

In [29]:
df = pd.read_csv('../.ipynb_checkpoints/emp.csv', parse_dates =['doj'], index_col='eno')

In [31]:
# sorting the data by creating own index columns
df.sort_index(ascending=False)

      ename  salary  deptno        doj
eno
12    Karan    2200      20 2018-06-06
11   Dennis   41000      30 2024-05-01
10    Amber    1000      10 2018-04-05
9     Naman    4000      30 2020-02-01
8     Sagar    1000      20 2020-03-11
7    Robert    3000      20 2023-02-05
6     Smith    1000      10 2016-01-12
5      Jade    2000      10 2021-10-02
4    Thomas    1000      10 2019-08-18
3      Nick    1000      30 2015-09-15
2      Amar    1000      10 2017-03-22
1     Vikas    1000      30 2017-10-03

In [35]:
# get me all the emp who joined in the year 2018 (without converting date formate we can't get it year)
df = pd.read_csv('../.ipynb_checkpoints/emp.csv', index_col ='eno')

In [34]:
df['doj'].dt.year

AttributeError: Can only use .dt accessor with datetimelike values

In [37]:
df = pd.read_csv('../.ipynb_checkpoints/emp.csv', parse_dates=['doj'], index_col ='eno')

In [38]:
df['doj'].dt.year

eno
1     2017
2     2017
3     2015
4     2019
5     2021
6     2016
7     2023
8     2020
9     2020
10    2018
11    2024
12    2018
Name: doj, dtype: int32

In [40]:
 df['doj'].dt.year == 2018

eno
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12     True
Name: doj, dtype: bool

In [41]:
year_2018 = df['doj'].dt.year == 2018

In [42]:
df[year_2018]

     ename  salary  deptno        doj
eno
10   Amber    1000      10 2018-04-05
12   Karan    2200      20 2018-06-06